name: Frontend CI

on: [push]

jobs:
  Frontend_Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install npm packages
      working-directory: ./frontend
      run: npm i
    - name: Ensure the frontend can build
      working-directory: ./frontend
      run: npm run build
    - name: Run Frontend test suite
      run: npm test
      working-directory: ./frontend
      env:
        CI: true
